### ISSUE TITLE
gcc/newlib fails to compile with "Unable to determine type definition of int32_t "

### ISSUE THREAD

**Issue by mithro** [timvideos/conda-hdmi2usb-packages#49]
```
libtool: compile:  /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/./gcc/xgcc -shared-libgcc -B/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/./gcc -nostdinc++ -L/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/src -L/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/src/.libs -L/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/libsupc++/.libs -B/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/bin/ -B/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/lib/ -isystem /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/include -isystem /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/sys-include -I/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include/lm32-elf -I/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include -I/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/work/work/gcc/libstdc++-v3/libsupc++ -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -fdata-sections -frandom-seed=compatibility-atomic-c++0x.lo -g -O2 -std=gnu++11 -c /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/work/work/gcc/libstdc++-v3/src/c++11/compatibility-atomic-c++0x.cc -o compatibility-atomic-c++0x.o

In file included from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/include/stdint.h:13:0,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/gcc/include/stdint.h:9,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include/bits/atomic_base.h:36,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include/atomic:41,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/work/work/gcc/libstdc++-v3/src/c++11/compatibility-atomic-c++0x.cc:26:

/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/include/sys/_intsup.h:68:2: error: #error "Unable to determine type definition of intptr_t"

 #error "Unable to determine type definition of intptr_t"

  ^

/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/include/sys/_intsup.h:75:2: error: #error "Unable to determine type definition of int32_t"

 #error "Unable to determine type definition of int32_t"

  ^

In file included from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/gcc/include/stdint.h:9:0,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include/bits/atomic_base.h:36,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include/atomic:41,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/work/work/gcc/libstdc++-v3/src/c++11/compatibility-atomic-c++0x.cc:26:

/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/include/stdint.h:55:22: error: conflicting declaration â€˜typedef int int_fast8_tâ€™

   typedef signed int int_fast8_t;

                      ^

In file included from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/work/work/gcc/libstdc++-v3/src/c++11/compatibility-atomic-c++0x.cc:25:0:

/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include/gstdint.h:103:22: note: previous declaration as â€˜typedef int8_t int_fast8_tâ€™

 typedef int8_t       int_fast8_t;

                      ^

In file included from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/gcc/include/stdint.h:9:0,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include/bits/atomic_base.h:36,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include/atomic:41,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/work/work/gcc/libstdc++-v3/src/c++11/compatibility-atomic-c++0x.cc:26:

/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/include/stdint.h:56:24: error: conflicting declaration â€˜typedef unsigned int uint_fast8_tâ€™

   typedef unsigned int uint_fast8_t;

                        ^

In file included from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/work/work/gcc/libstdc++-v3/src/c++11/compatibility-atomic-c++0x.cc:25:0:

/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include/gstdint.h:110:22: note: previous declaration as â€˜typedef uint8_t uint_fast8_tâ€™

 typedef uint8_t      uint_fast8_t;

                      ^

/bin/bash ../libtool --tag CXX   --mode=compile /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/./gcc/xgcc -shared-libgcc -B/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/./gcc -nostdinc++ -L/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/src -L/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/src/.libs -L/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/libsupc++/.libs -B/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/bin/ -B/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/lib/ -isystem /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/include -isystem /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/sys-include     -I/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include/lm32-elf -I/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include -I/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/work/work/gcc/libstdc++-v3/libsupc++   -fno-implicit-templates  -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi  -fdiagnostics-show-location=once   -ffunction-sections -fdata-sections  -frandom-seed=compatibility-thread-c++0x.lo -g -O2  -std=gnu++11 -c /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/work/work/gcc/libstdc++-v3/src/c++11/compatibility-thread-c++0x.cc

libtool: compile:  /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/./gcc/xgcc -shared-libgcc -B/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/./gcc -nostdinc++ -L/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/src -L/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/src/.libs -L/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/libsupc++/.libs -B/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/bin/ -B/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/lib/ -isystem /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/include -isystem /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/sys-include -I/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include/lm32-elf -I/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include -I/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/work/work/gcc/libstdc++-v3/libsupc++ -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -fdata-sections -frandom-seed=compatibility-thread-c++0x.lo -g -O2 -std=gnu++11 -c /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/work/work/gcc/libstdc++-v3/src/c++11/compatibility-thread-c++0x.cc -o compatibility-thread-c++0x.o

In file included from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/include/stdint.h:13:0,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/gcc/include/stdint.h:9,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include/bits/atomic_base.h:36,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include/bits/shared_ptr_atomic.h:33,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include/memory:83,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include/thread:40,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/include/future:40,

                 from /tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/work/work/gcc/libstdc++-v3/src/c++11/compatibility-thread-c++0x.cc:30:

/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/include/sys/_intsup.h:68:2: error: #error "Unable to determine type definition of intptr_t"

 #error "Unable to determine type definition of intptr_t"

  ^

/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lm32-elf/include/sys/_intsup.h:75:2: error: #error "Unable to determine type definition of int32_t"

 #error "Unable to determine type definition of int32_t"

  ^

make[5]: *** [compatibility-atomic-c++0x.lo] Error 1

make[5]: *** Waiting for unfinished jobs....

make[5]: *** [compatibility-thread-c++0x.lo] Error 1

make[5]: Leaving directory `/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/src'

make[4]: *** [all-recursive] Error 1

make[4]: Leaving directory `/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3/src'

make[3]: *** [all-recursive] Error 1

make[3]: Leaving directory `/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3'

make[2]: *** [all] Error 2

make[2]: Leaving directory `/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc/lm32-elf/libstdc++-v3'

make[1]: *** [all-target-libstdc++-v3] Error 2

make[1]: Leaving directory `/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/build-gcc'

make: *** [all] Error 2

Traceback (most recent call last):

  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/bin/conda-build", line 11, in <module>

    sys.exit(main())

  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 424, in main

    execute(sys.argv[1:])

  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 415, in execute

    verify=args.verify)

  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/api.py", line 201, in build

    notest=notest, need_source_download=need_source_download, variants=variants)

  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/build.py", line 2205, in build_tree

    notest=notest,

  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/build.py", line 1445, in build

    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)

  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/utils.py", line 311, in check_call_env

    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)

  File "/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/lib/python3.7/site-packages/conda_build/utils.py", line 291, in _func_defaulting_env_to_os_environ

    raise subprocess.CalledProcessError(proc.returncode, _args)

subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/tmp/really-really-really-really-really-really-really-really-really-really-really-really-really-long-path/conda/conda-bld/gcc-lm32-elf-newlib_1537237721697/work/conda_build.sh']' returned non-zero exit status 2.
```

**Comment by mithro** [comment]
This is fixed by https://github.com/timvideos/conda-hdmi2usb-packages/blob/master/gcc/newlib/stdint.patch
